[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
Maid = "nightcycle/maid@1.1.4"
MockMemoryStoreService = "vorlias/mock-memory-store-service@0.2.0"
CompressionUtil = "nightcycle/compression-util@1.0.0"
Signal = "nightcycle/signal@1.0.2"
TableUtil = "nightcycle/table-util@1.1.0"
DictionaryPathUtil = "nightcycle/dictionary-path-util@1.0.0"
MockMessagingService = "nightcycle/mock-messaging-service@1.0.1"